### ISSUE TITLE
Package plugins for offline installation

### ISSUE THREAD

**Issue by russcam** [elastic/windows-installers#12]
Currently, the installer requires an active Internet connection in order to be able to install any plugins. This presents problems in air-gapped scenarios, which are common in security-heavy organizations. We could package the available plugins with the installer and install them from there to address this. The downside is the install size could grow significantly, so if/when we do this, we may want to consider creating separate installers for online and offline situations.

Not a blocker for MVP, but leaving it here for future discussion.

**Comment by askids** [comment]
Here is a suggestion. Don't package any of the components as part of the msi - not even Elasticsearch. Instead add parameters which will just point to the zip file location (assuming everything for windows comes as zip). So that way, a new msi need not be built out every time. People will just need to download the new versions directly from Elastic site and update their config files. 

Apart from one off installations on individual machines where the UI will be used to go through the entire step by step process, in most of the cases, organizations will use silent install for deploying Elasticsearch on servers. So one more suggestion (probably need to track this as independent item) would be to support a config file that can hold all the parameters and pass it to the installer, instead of individually passing them to MSIEXEC as parameters. Something like esinstaller.msi CONFIGPATH="C:\Temp\Myconfig.ini". Not sure if MSIEXEC supports this. But installshield does.

**Comment by russcam** [comment]
> Don't package any of the components as part of the msi - not even Elasticsearch.

One of the reasons for packaging Elasticsearch files in the MSI is that MSI installation 

1. handles calculating the installation size, failing if there is insufficient space
2. handles deployment and cleanup of files
3. handles upgrades to newer versions of the MSI

> Apart from one off installations on individual machines where the UI will be used to go through the entire step by step process, in most of the cases, organizations will use silent install for deploying Elasticsearch on servers.

Agreed; the MSI will be useful for those who'd like to get started in using Elasticsearch on Windows, which is where the UI wizard will be helpful, but also those organizations that are running Elasticsearch on Windows in production, who'll likely be performing silent installations, perhaps using a package manager like chocolatey.

> So one more suggestion (probably need to track this as independent item) would be to support a config file that can hold all the parameters and pass it to the installer, instead of individually passing them to MSIEXEC as parameters. Something like esinstaller.msi CONFIGPATH="C:\Temp\Myconfig.ini". Not sure if MSIEXEC supports this. But installshield does.

MSIEXEC as far as I know doesn't have an in-built property for a configuration file but I think this would be really useful to add.

**Comment by Mpdreamz** [comment]
back on topic: I spiked this last week but all of the plugins together is ~300mb, the idea of acquiring parts online during installation is not that foreign in the tooling space IMO. 

Should we close this?

**Comment by russcam** [comment]
At 300MB, Makes sense. We can revisit in the future if need be.

**Comment by codebrain** [comment]
Addressed in https://github.com/elastic/windows-installers/pull/185
