### ISSUE TITLE
An error occured during installation

### ISSUE THREAD

**Issue by hanxinimm** [elastic/windows-installers#148]
[logs.txt](https://github.com/elastic/windows-installers/files/1543194/logs.txt)

**Comment by fanglijun** [comment]
看看是不是被杀毒软件拦截了 @hanxinimm

**Comment by russcam** [comment]
Hey @hanxinimm. The install log indicates that the installation failed because the Windows Service did not start within 1 minute:

> System.ServiceProcess.TimeoutException: Timeout has expired and the operation has not been completed in 00:01:00.
>    ÔÚ Elastic.Installer.Domain.Configuration.Service.ServiceStateProvider.StartAndWaitForRunning(TimeSpan timeToWait, Int32 totalTicks)
>    ÔÚ Elastic.InstallerHosts.Elasticsearch.Tasks.Install.StartServiceTask.ExecuteTask()
>    ÔÚ Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchServiceStartAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> Action ended 0:03:34: InstallFinalize. Return value 3.

As a workaround, I recommend to install as a Windows Service _but_ configure it **not** to start as part of the installation, then start the service afterwards from the Service Control Panel.

Closing this in favour of #135
