### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mrinalkamboj** [elastic/windows-installers#150]
[MSI915d.LOG](https://github.com/elastic/windows-installers/files/1559422/MSI915d.LOG)

Error in installation of the Elastic search, please review, attached the log, not able to install the latest download

**Comment by russcam** [comment]
Hey @mrinalkamboj. The install log indicates that the installation failed because the Windows Service did not start within 1 minute:

> 0] waiting to start waiting to start
> [0] waiting to start waiting to start
> System.ServiceProcess.TimeoutException: Timeout has expired and the operation has not been completed in 00:01:00.
>    at Elastic.Installer.Domain.Configuration.Service.ServiceStateProvider.StartAndWaitForRunning(TimeSpan timeToWait, Int32 totalTicks)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.StartServiceTask.ExecuteTask()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchServiceStartAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> Action ended 19:22:17: InstallFinalize. Return value 3.

As a workaround, I recommend to install as a Windows Service _but_ configure it **not** to start as part of the installation, then start the service afterwards from the Service Control Panel.

Closing this in favour of #135
