### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by rahulblue** [elastic/windows-installers#152]
error occured during installation
![image](https://user-images.githubusercontent.com/16150494/34098081-3b6b03be-e401-11e7-8c58-c5ffbe90877a.png)
installation log
[MSI7b3c5.LOG](https://github.com/elastic/windows-installers/files/1567244/MSI7b3c5.LOG)

**Comment by russcam** [comment]
Hey @rahulblue. The install log indicates that the installation failed because the Windows Service did not start within 1 minute:

> [0] waiting to start waiting to start
> [0] waiting to start waiting to start
> [0] waiting to start waiting to start
> [0] waiting to start waiting to start
> [0] waiting to start waiting to start
> System.ServiceProcess.TimeoutException: Timeout has expired and the operation has not been completed in 00:01:00.
>    at Elastic.Installer.Domain.Configuration.Service.ServiceStateProvider.StartAndWaitForRunning(TimeSpan timeToWait, Int32 totalTicks)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.StartServiceTask.ExecuteTask()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchServiceStartAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> Action ended 14:34:44: InstallFinalize. Return value 3.

As a workaround, I recommend to install as a Windows Service _but_ configure it **not** to start as part of the installation, then start the service afterwards, from the Service Control Panel.

This issue should be addressed in the 6.1.1 installer release.

Closing this in favour of #135 where this issue is being tracked.
