### ISSUE TITLE
The Elasticsearch service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs

### ISSUE THREAD

**Issue by mcshekhar** [elastic/windows-installers#155]
[MSIdb4cc.LOG](https://github.com/elastic/windows-installers/files/1584730/MSIdb4cc.LOG)
The Elasticsearch service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs

### Environment
Windows 10

### Steps to reproduce the behaviour

1. Installed the "elasticsearch-6.1.1.msi' file after downloading.
2. Installed Elastic Search as a service.
3. The service stops automatically.

**Comment by gbukauskas** [comment]
I met the same problem with old version of ES running on Window 10. Reinstalled Java SE and Elastic Search but got the failure.

**Comment by russcam** [comment]
Hey @mcshekhar 

Looking at the log, the error is related to the installer being unable to start the Windows Service as part of installation:
```
MSI (s) (D4:78) [15:14:27:265]: Product: Elasticsearch 6.1.1 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
```
The installer is set to run the service under the [`LocalSystem` account ](https://msdn.microsoft.com/en-us/library/ms684190(v=VS.85).aspx). Do you have a Policy configured (Local or Group) that prevents Windows Services from running under the LocalSystem account? Since LocalSystem account has a lot of privileges, it can be common for organisations to prevent services from running under this account.

Is there any additional information in the Windows Event log?

A couple of things to try

1. Installing as a service but setting not to start as part of the installation. Then start the service after installation has succeeded. If this works, it would indicate a different issue to a configured Policy for LocalSystem.
2. Setting up a new account to run the Elasticsearch service, giving the account privileges to run the Elasticsearch service and read/write/execute access to the installation/data/config/logs directories.

Let me know the outcome of these if you try them.

**Comment by codebrain** [comment]
Closing as OP has not responded.

**Comment by samarqhand** [comment]
Since this page ranks well for searches for the error message am I okay to leave a note that might help others?

I had the error "The Elasticsearch service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs" 

And looking at the event log it showed that Java couldn't be found, an update had changed the path to Java but not updated the system env for JAVA_HOME. Editing that manually fixed my issue.

**Comment by codebrain** [comment]
Thanks @samarqhand
