### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by ashokkuxilinx** [elastic/windows-installers#162]
### Steps to reproduce the behaviour

1.
2.
3.

**Comment by russcam** [comment]
I'm closing this issue because [per the issue guidelines](https://raw.githubusercontent.com/elastic/windows-installers/master/.github/issue_template.md), it does not provide the installation log file nor any detail to ascertain why the installer may have failed.

Feel free to reopen this issue if this information is provided @ashokkuxilinx.
