### ISSUE TITLE
MSI installer 6.3.0 - occasional error message

### ISSUE THREAD

**Issue by pheyos** [elastic/windows-installers#181]
**Found in version**
6.3.0-SNAPSHOT

**Steps to reproduce**
Currently there is no known reproduction for this issue.
During tests the following message showed up a few times in completely different situations (a few seconds after following the license link, a few minutes after navigating to the plugins list and then ALT+TAB out of the virtual machine to do something else, …):

![msi_installer_not_responding](https://user-images.githubusercontent.com/1945390/38940922-a6aecfe6-432b-11e8-950e-9301279e0530.png)

**Comment by pheyos** [comment]
Environment details:
- GCP instance: `n1-standard-2 (2 vCPUs, 7.5 GB memory)`
- OS: `Windows Server 2016 Datacenter` Version `1607` OS Build `14393.2189`

Issue details:
- In a most of the cases it happened after a longer period of inactivity (~15 minutes, but didn't count the time)
- In one of the cases it happened after navigating around in the UI for some minutes (certainly more than 10, but again didn't count the time) and then opening the license link in a browser. About 5 seconds after the application switch the message popped up. In this scenario there was no longer period of inactivity.
- I tried to reproduce both scenarios but with no success.

@russcam  let me know if you need more/other details.

**Comment by russcam** [comment]
Thanks @pheyos. From what I can see, this dialog is triggered by the installer engine (msiexec.exe), after a period of 10 minutes of inactivity. The UI is an external UI WPF application, with a separate process launched to surface it. 

Based on your description, it would appear that the External UI does not report back to the installer engine to indicate activity. I don't think this issue is a big one right now, but it would be good to investigate to see if there are options to mitigate.

**Comment by codebrain** [comment]
I've looked into this and it seems this is the behaviour of the MSI install engine. Closing as I'm not sure we can actually override this behaviour and it seems like a rare occurrence.
