### ISSUE TITLE
Failed during installation using MSI on Win 10

### ISSUE THREAD

**Issue by Viltersten** [elastic/windows-installers#246]
### Environment

Not behind proxy. Stockholm Sweden.

### Expected Behaviour
INstallation success.
### Actual Behaviour
Not isntalled, no directories created.
### Steps to reproduce the behaviour
DOuble click on MSI file.

Fresh.
1.
2.
3.

**Comment by Viltersten** [comment]
[MSIb3a73.LOG](https://github.com/elastic/windows-installers/files/2601158/MSIb3a73.LOG)

**Comment by core01** [comment]
I have the same issue.

### Steps to reproduce the behavior
Install Elasticsearch from MSI with default options (no additional options selected)
### Environment
Elasticsearch v6.5.1
Windows 10 x64
No proxy
Asia/Kazakhstan
Expected Behavior
Installation success.

Installation log file: https://gist.github.com/core01/6016bb3319a8673c38b8ffd34777cdc6
No elasticsearch log file available
### Additional information


Installation stuck on `Starting elasticsearch service windows`
![](https://image.prntscr.com/image/-CwJsF3VTuiY0igRMCvJdw.jpeg)
 than `An error occurred during installation`
![](https://image.prntscr.com/image/QG2Ce8BEThSYG8GuEZzzdw.jpeg)

**Comment by russcam** [comment]
@core01 

The issue from the log file is

```
Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
MSI (s) (58:3C) [10:37:50:929]: Note: 1: 2205 2:  3: Error 
MSI (s) (58:3C) [10:37:50:929]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (58:3C) [10:37:50:929]: Product: Elasticsearch 6.5.1 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
```

**Comment by russcam** [comment]
@Viltersten 

The issue from the log file is

```
[0] installing installing
System.InvalidOperationException: The installation failed, and the rollback has been performed. ---> System.ComponentModel.Win32Exception: The trust relationship between this workstation and the primary domain failed
   at System.ServiceProcess.ServiceProcessInstaller.GetAccountSid(String accountName)
   at System.ServiceProcess.ServiceProcessInstaller.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at Elastic.Installer.Domain.Configuration.Service.ServiceInstallationManager.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   --- End of inner exception stack trace ---
   at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   at Elastic.Installer.Domain.Configuration.Service.ServiceInstallationManager.RuntimeInstall(ServiceConfiguration configuration)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.InstallServiceTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
```

This is for the the username you used in the `cdongroup` domain. 

There are a number of reasons why this might happen, but it is possible that the credentials on your computer are out of sync with the domain controllers (can happen when a password is changed only locally). I would recommend either reestablishing trust between your workstation and the primary domain, and trying the installer again, or try to install as a Windows Service with a different set of credentials.

**Comment by core01** [comment]
@russcam Hello, thank you for error description. But if I run CMD as Administrator and launch msi from cmd I still cannot finish installation and I've get the same error.
But if I check "Do not install as service" option - installation finished successfully.

I understand that this issue is more windows related, but I'm only one user at my PC and I can install other third party services such as OpenVPN, Mozilla maintenance and Nvidia Display without any workarounds.

**Comment by hustcsxg** [comment]
check java is installed, open cmd  >> java -verbose --version   add  JAVA_HOME to env

**Comment by core01** [comment]
@codebrain what response are you waiting?
MSI checks JAVA in the beginning of the installation process

I'm switched to zip version

**Comment by hustcsxg** [comment]
@codebrain  first time when i setup faild for a miss java_home ,when i set JAVA_HOME env  setup successfull but when i use, cmd tell me  can't not create java virtual env。then i setup in centos7 got some problems and solved.

**Comment by pmatula** [comment]
> @codebrain what response are you waiting?
> MSI checks JAVA in the beginning of the installation process and I would not get to the service installation phase without correct JAVA_HOME env
> 
> I'm switched to zip version

I had (more or less) the same issue. 
My problem was, I had my PATH variable set to C:\Program Files\Java\jdk1.8.0_202\bin. Run java from cmd works fine. But my JAVA_HOME variable was set to the same path.

Eventviewer showed the issue, because elasticsearch.exe used JAVA_HOME and wanted to start: C:\Program Files\Java\jdk1.8.0_202\bin\bin\java.exe 

Fixed JAVA_HOME -> Starting service worked fine.

**Comment by russcam** [comment]
> Eventviewer showed the issue, because elasticsearch.exe used JAVA_HOME and wanted to start: C:\Program Files\Java\jdk1.8.0_202\bin\bin\java.exe
> 
> Fixed JAVA_HOME -> Starting service worked fine.

`JAVA_HOME` should always be the path to the java installation, and not to the `bin` directory in the java installation 👍
