### ISSUE TITLE
Windows MSI 6.6.1 installation failure

### ISSUE THREAD

**Issue by jehandwerker** [elastic/windows-installers#262]
### Environment
Window 10 Pro Version 1803 OS build 17134.590
### Expected Behaviour
Install Elasticsearch
### Actual Behaviour
Failed Installation
### Steps to reproduce the behavior

Fresh install

1. Launched elasticsearch-6.6.1.msi
2. Shown end screen saying install failed

Log attached
[MSIaea06.LOG](https://github.com/elastic/windows-installers/files/2895488/MSIaea06.LOG)

**Comment by piaozhegao** [comment]
I also failed to install elasticsearch-6.6.1.msi, 
my OS is Window 10

this is install failed log :

SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSICFEE.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchPluginsAction.ElasticsearchPlugins
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing ingest-attachment installing ingest-attachment
\Common은(는) 예상되지 않았습니다.
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.6.1\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Common은(는) 예상되지 않았습니다.

   위치: Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   위치: Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   위치: Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   위치: Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 9:35:01: InstallFinalize. Return value 3.
MSI (s) (90:8C) [09:35:01:492]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (90:8C) [09:35:01:493]: User policy value 'DisableRollback' is 0
MSI (s) (90:8C) [09:35:01:493]: Machine policy value 'DisableRollback' is 0

**Comment by Mpdreamz** [comment]
> \Common was unexpected at this time.
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.6.1\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Common was unexpected at this time.

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)


This is a known issue that will be fixed when https://github.com/elastic/elasticsearch/pull/39712 is fixed in Elasticsearch itself.

And for our own housekeeping: duplicate of: https://github.com/elastic/windows-installers/issues/252
