### ISSUE TITLE
Failed GUI Installation 7.0.0

### ISSUE THREAD

**Issue by jerepigo** [elastic/windows-installers#286]
### Environment

No
 New Zealand

### Expected Behaviour
Completion of the basic installation with a few custom directory selections

### Actual Behaviour
Failure to complete installation

### Steps to reproduce the behaviour

 Fresh installation

1.
2.
3.

**Comment by russcam** [comment]
Hi @jerepigo , 

Please attach the MSI log file for the failed installation; a log file for the installation process can be found within the `%TEMP%` directory, with a randomly generated name adhering to the format `MSI<random>.LOG`. Without this log file, it's not possible to determine why the installation failed.

**Comment by jerepigo** [comment]
It was attached as part of the ticket logging process, else I would have
attached it if I had actually emailed the case.
If this has failed I will simply close the ticket and attempt install via
packages instead.
I hste repeating things when they don't work as expected.

**Comment by russcam** [comment]
> It was attached as part of the ticket logging process, else I would have
attached it if I had actually emailed the case.

Which ticket logging process are you referring to?

I'm closing this issue because without the installation log, there's no way to determine what the issue might be. if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍
