### ISSUE TITLE
MSI Install failing

### ISSUE THREAD

**Issue by hemant-elastic** [elastic/windows-installers#291]
### Environment

Windows 2016 Server on Azure VM

### Actual Behaviour

MSI installer failing

### Steps to reproduce the behaviour

Fresh Install. Experienced for both 6.7.1 and 7.0.0 MSI installer

1. Install Java - installed at (C:\Java) [ It was required by 7.0.0 installer ]
2. Install Elasticsearch using MSI installer

[install.log](https://github.com/elastic/windows-installers/files/3096600/install.log)

<img width="603" alt="50C8EF21-52D0-4A01-B1CD-A8DCA6FEA377" src="https://user-images.githubusercontent.com/26748353/56398781-4e510c80-61ff-11e9-85d5-111099d5ce27.png">

**Comment by AArgumedo** [comment]
I had the same error, according to event viewer it was caused by one of the attachments. 
"System.Exception: Execution failed (D:\Program Files\Elasticsearch\7.0.0\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 0 ErrorCheck: True ErrorOut:WARNING: An illegal reflective access operation has occurred"

So i removed it from the install selection,
Then i had the same error about the second plugin I selected, so I also removed,
 "System.Exception: Execution failed (D:\Program Files\Elasticsearch\7.0.0\bin\elasticsearch-plugin.bat install ingest-geoip --batch). ExitCode: 64 ErrorCheck: False ErrorOut:"

And then finished installing with no issues, it seems to be an issue adding the plugins from the initial installation. I'll try to install them later.

**Comment by mjj203** [comment]
Same issue with MSI.
[ES7_MSI_ErrorInstalling.log](https://github.com/elastic/windows-installers/files/3102100/ES7_MSI_ErrorInstalling.log)

**Comment by hemant-elastic** [comment]
Hi @AArgumedo , unfortunately the overall install failed for me again even after deselecting the plugins during the install. Glad to know that fixed it for you.

**Comment by ygel** [comment]
```[0] installing ingest-attachment installing ingest-attachment
Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co
```

#311

**Comment by Phrozyn** [comment]
I'm also seeing this error on Windows 10, I have the murmur3, mapper size, and ingest-attachment plugins selected. 

`System.Exception: Execution failed (E:\Program Files\Elastic\Elasticsearch\7.2.0\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 0 ErrorCheck: True ErrorOut:WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/E:/Program%20Files/Elastic/Elasticsearch/7.2.0/lib/tools/plugin-cli/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 11:06:12: InstallFinalize. Return value 3.`
