### ISSUE TITLE
An error occurred during installation! Elasticsearch 7.2.0

### ISSUE THREAD

**Issue by MohammedUzair** [elastic/windows-installers#313]
[MSI4f5d1_install_log.txt](https://github.com/elastic/windows-installers/files/3353872/MSI4f5d1_install_log.txt)

### Environment

No

South Africa

### Steps to reproduce the behaviour

1.This is a fresh install.
2.
3.

 Screenshot attached.
![Elasticsearch7 2 0_error](https://user-images.githubusercontent.com/34092265/60575153-5559d680-9d7b-11e9-95cb-8bfa59868b65.JPG)

**Comment by russcam** [comment]
The error is

> Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
MSI (s) (14:5C) [10:03:14:281]: Note: 1: 2205 2:  3: Error 
MSI (s) (14:5C) [10:03:14:281]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (14:5C) [10:03:14:281]: Product: Elasticsearch 7.2.0 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.

There could be a few reasons for this. Could you try installing again, but *not* as a Windows service, and starting up `elasticsearch.exe` manually from an Administrative command prompt? If it fails, please can you provide the error message text and the contents of the elastisearch log file in the specified logs location?

**Comment by MohammedUzair** [comment]
Hi Russcam,

Thanks for responding to my support request.
I ran the installation again (not as Windows service) as you suggested and the install completed successfully, which is great!

There is an error message when I attempt to start elasticsearch.exe from an Administrative command prompt - please see below.

C:\Program Files\Elastic\Elasticsearch\7.2.0\bin>.\elasticsearch.exe
Could not evaluate jvm.options file: C:\ProgramData\Elastic\Elasticsearch\config\jvm.options result: Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.004s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.004s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)


What can I do here to ensure elasticsearch is able to start java?
Is there something I should change on the jvm,options file?

**Comment by UkrZilla** [comment]
Comment this line:

`9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m`

**Comment by russcam** [comment]
The problem is that the logs directory into which the GC log will be placed does not exist. 

With Elasticsearch 7.x less than 7.2.0, the elasticsearch.exe would create the logs directory as a sibling of the `%ES_HOME/bin` directory, irrespective of the current working directory. 

In 7.2.0, a change has been made in Elasticsearch that runs a Java process before starting Elasticsearch, to determine the final JVM options to run with. As part of running this process, the jvm.options file is used, which expects to place GC log in `logs/gc.log`. Since the logs directory does not exist, this process errors _before_ elasticsearch.exe has a chance to run and create the logs directory.

If a logs directory is created in `%ES_HOME%` and elasticsearch.exe is started from `%ES_HOME%`

```sh
C:\Program Files\Elastic\Elasticsearch\7.2.0> .\bin\elasticsearch.exe
```

It will start successfully. We'll fix this in a later release.

> Comment this line:
> 
> 9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m

Rather than doing this, it'd be better to point the GC log to a directory that exists, for example, assuming `c:\logs` directory is created

```sh
9-:-Xlog:gc*,gc+age=trace,safepoint:file=C:/logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
```

or create a logs directory in the `%ES_HOME%/bin` directory.

**Comment by MohammedUzair** [comment]
Issue is resolved. Elasticsearch is up and running!
Thanks for your help Russ!
