### ISSUE TITLE
Allow options for basic|trial license generation on x-pack install

### ISSUE THREAD

**Issue by eskibars** [elastic/windows-installers#99]
The title pretty much says it all.  As a follow-up, it'd be great if we could actually do more license management for them (upload a license key from a file they select), but this seems like a good first step

**Comment by skearns64** [comment]
@russcam - when you start ES for the first time after installing X-Pack, it will automatically detect that there is no license and that it hasn't self-generated a license yet, and will generate a 30-day license of type `trial`. However, there is an optional setting that will cause the self-generated license to be of type `basic`. 

If/when we change to install X-Pack by default, we would want the default be to self-generate a `basic` license - that way, all free capabilities will be installed and available by default. I believe this issue is about making sure that as part of the installer, the user can opt for a 30-day `trial` license rather than a `basic` license. 

Note that we're now adding a proper License Management UI to Kibana in 6.1, so I think the importance of having the MSI installer provide a similar capability is quite a bit lower.

**Comment by russcam** [comment]
@skearns64 the capability to choose a trial or basic license has been implemented in the installer for 6.0.0-rc2 and [is available in the MSI on the prerelease download](https://www.elastic.co/downloads/elasticsearch#preview-release).

I'll open a separate issue for uploading a license so as not to muddy the waters  on this issue 👍

**Comment by russcam** [comment]
I've opened #126 for uploading a license
